on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git show $(git describe --tags `git rev-list --tags --max-count=1`):src/Badges.sol > src/Badges.sol.last_tagged
      - run: diff src/Badges.sol src/Badges.sol.last_tagged > src/Badges.sol.diff
      - run: if [[ -s src/Badges.sol.diff ]]; then echo "THERES A DIFF!!!"; fi
      - run: |
          version=$(grep '"version":' package.json | cut -d'"' -f4)
          git tag $version
          git push origin $version
