on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # Find the commit that corresponds to the last tag
          last_tag_commit=$(git log --decorate --tags --simplify-by-decoration --pretty="format:%H" | head -1)
          # Display the contents of src/Badges.sol at the commit corresponding to the last tag
          git show $last_tag_commit:src/Badges.sol
      - run: |
          version=$(grep '"version":' package.json | cut -d'"' -f4)
          git tag $version
          git push origin $version
