on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          # Check out the commit at the last tag
          git checkout $(git describe --abbrev=0 --tags)

          # Save the contents of src/Badges.sol at the last tag to a temporary file
          git show HEAD:src/Badges.sol > last_tag_badges.sol

          # Check out the current commit
          git checkout HEAD

          # Compare src/Badges.sol at the last tag with the current version
          diff -q src/Badges.sol last_tag_badges.sol
          if [ $? -ne 0 ]; then
            echo "DIFFERENT"
          fi

          # Clean up the temporary file
          rm last_tag_badges.sol

      - run: |
          version=$(grep '"version":' package.json | cut -d'"' -f4)
          git tag $version
          git push origin $version
