on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          latest_tag=$(git for-each-ref --sort=-taggerdate --format '%(refname:short)' refs/tags | tail -n 1)

          git checkout $latest_tag

          latest_badges=$(cat src/Badges.sol)

          git checkout HEAD

          current_badges=$(cat src/Badges.sol)

          if [ "$latest_badges" != "$current_badges" ]; then
              echo "ITS DIFFERENT!"
          fi
      - run: |
          version=$(grep '"version":' package.json | cut -d'"' -f4)
          git tag $version
          git push origin $version
